config/routes.rb
Incarnateword::Application.routes.draw do
  class DoclistConstraints
    def matches?(params)
      a = b = c = d = true
      a_name = a_year = name_used = false
      if !!(/^m$|^sa$/).match(params[:a])
        a_name = true
      elsif !!(/^\d{4}$/.match(params[:a])) && params[:a].to_i.between?(
        1872, 1973)
        a_year = true
      end
      a = a_name || a_year
      if params[:b]
        b = (!!(/^\d|\d{2}$/.match(params[:b])) && params[:b].to_i.between?(
          1, 12)) || !a_name && !!(/^m$|^sa$/).match(params[:b]) ? true : false
        if params[:c]
          c = (!!(/^\d{2}$/.match(params[:c])) && params[:c].to_i.between?(
            1, 31)) || !a_name && !!(/^m$|^sa$/).match(
              params[:c]) ? true : false
          if params[:d]
            d = !!(/^m$|^sa$/.match(params[:d])) && !a_name
          end
        end
      end
      a && b && c && d
    end
  end

  class CompilationConcordanceConstraints
    def matches?(params)
      if params.subdomain.empty? || params.subdomain == 'www'
        compilation = alpha = true
        compilations = %w(sabcl cwsa arya cwm cwmfr agenda agendafr)
        unless compilations.include?(params[:compilation])
          return false
        end
        if params[:a]
          return params[:a].match(/[a-z&]/)
        end
        true
      else
        false
      end
    end
  end

  class CompilationConstraints
    def matches?(params)
      if params.subdomain.empty? || params.subdomain == 'www'
        compilation = volume = alpha = true
        compilations = %w(sabcl cwsa arya cwm cwmfr agenda agendafr)
        unless compilations.include?(params[:compilation])
          return false
        end
        if params[:volume]
          volume = (!!(/^\d|\d{2}$/.match(params[:volume])) && params[:volume].to_i.between?(
            1, 37)) ? true : false
        end
        if params[:a]
          alpha = params[:a].match(/[a-z&]/)
        end
        return compilation && volume && alpha
      else
        false
      end
    end
  end

  class AuthorConstraints
    def matches?(params)
      if params.subdomain.empty? || params.subdomain == 'www'
        authors = %w(sa m)
        return true if authors.include?(params[:author])
        return false
      else
        false
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy', as: 'signout'

  get '/' => 'entries#index', constraints: { subdomain: 'dictionary' }, as: 'dictionary'
  get '/entries', to: 'entries#index', constraints: { subdomain: 'dictionary' }
  get '/:id', to: 'entries#show', constraints: { subdomain: 'dictionary' }, as: 'dictionary_entry'

  get '/:author', to: 'authors#show', constraints: AuthorConstraints.new

  resources :entries, :books, :chapters, :home, :quotes

  get '/:compilation', to: 'compilations#show', constraints: CompilationConstraints.new
  get '/:compilation/concordance', to: 'compilations#concordance', constraints: CompilationConcordanceConstraints.new
  get '/:compilation/concordance/:a', to: 'compilations#concordance_alpha', constraints: CompilationConcordanceConstraints.new

  get '/:compilation/:volume', to: 'volumes#show', constraints: CompilationConstraints.new, as: 'compilation_vol'
  get '/:compilation/:volume/concordance', to: 'volumes#concordance', constraints: CompilationConstraints.new
  get '/:compilation/:volume/concordance/:a', to: 'volumes#concordance_alpha', constraints: CompilationConstraints.new
  get '/:compilation/:volume/:url', to: 'chapters#show', constraints: CompilationConstraints.new, as: 'compilation_chapter'

  get '/get_asset_digest', to: 'digests#get'

  root to: "home#index"

end

app/views/layouts/_ga.html.erb
<script>
  if (window.ga == undefined) {
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-47861759-1', 'auto');
  }
  if (gon.prerender) {
    ga('send', 'pageview');
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<% device_type = request.env['mobvious.device_type'].to_s %>
<html lang='en' <%= device_type != 'mobile' ? 'class=top-padding' : '' %>>
<head>
  <% if params['_escaped_fragment_'].nil? %>
    <title>The Incarnate Word</title>
  <% else %>
    <title><%= page_title %>The Incarnate Word</title>
  <% end %>
  <%= yield :head %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= requirejs_include_tag "application" do { "turbolinks-track" => true } end %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body data-device-type=<%= device_type %>>
  <%= include_gon %>
  <header class="navbar navbar-default <%= device_type == 'mobile' ? 'navbar-static-top' : 'navbar-fixed-top' %> navbar-custom" role="navigation">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="dropdown js-toc-dropdown"></div>
            <%= link_to 'The Incarnate Word', root_url(subdomain: ''), class: 'navbar-brand' %>
          </div>
          <nav class="collapse navbar-collapse no-transition" id="nav-collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown <%= 'active' if sri_aurobindo %>">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Sri Aurobindo <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'About', root_url(subdomain: '') + 'sa', class: "dropdown-toggle" %></li>
                  <li role="presentation" class="divider"></li>
                  <li><%= link_to 'Birth Centenary Library', root_url(subdomain: '') + 'sabcl', class: "dropdown-toggle" %></li>
                  <li><%= link_to 'Complete Works', root_url(subdomain: '') + 'cwsa', class: "dropdown-toggle" %></li>
                </ul>
              </li>
              <li class="dropdown <%= 'active' if mother %>">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  The Mother <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'About', root_url(subdomain: '') + 'm', class: "dropdown-toggle" %></li>
                  <li role="presentation" class="divider"></li>
                  <li><%= link_to 'Collected Works', root_url(subdomain: '') + 'cwm', class: "dropdown-toggle" %></li>
                  <li><%= link_to 'Agenda', root_url(subdomain: '') + 'agenda', class: "dropdown-toggle" %></li>
                </ul>
              </li>
              <li class="<%= 'active' if params[:controller] == 'entries' %>"><%= link_to 'Dictionary', root_url(subdomain: 'dictionary') %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-twitter"></i> <%=  current_user.handle %> <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-custom">
                    <li><%= link_to 'Sign out', signout_path %></li>
                  </ul>
                </li>
              <% else %>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    Sign in <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-custom">
                    <li><a href='/auth/twitter'><i class="fa fa-twitter"></i> Twitter</a></li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <div class="container-top">
    <div class="container">
      <div class="row row-body">
        <div class="col-sm-1 js-sharebar col-lg-offset-1 text-center"></div>
        <div class="col-lg-8 col-md-10 js-content <%= device_type == 'mobile' ? 'xs-wide' : '' %>">
          <%= yield %>
          <div id="context-menu" style="position: absolute; z-index: 9999; top: 296px; left: 285px;" class="">
            <ul class="dropdown-menu" role="menu" style="font-size: smaller;cursor: pointer">
              <li class="js-add-quote"><a tabindex="-1">Add to quotes</a></li>
              <li class="js-add-tags" data-list="list"><a tabindex="-1" data-anchor="anchor" class="js-add-tag-anchor">Add tags</a></li>
              <!-- <input type="text" placeholder="Tags"> -->
              <!--  <li><a tabindex="-1">Another action</a></li>
               <li><a tabindex="-1">Something else here</a></li>
               <li class="divider"></li>
               <li><a tabindex="-1">Separated link</a></li> -->
            </ul>
          </div>
          <div class="modal fade quote-tags-modal" tabindex="-1" role="dialog" aria-labelledby="add-quote-tags" aria-hidden="true">
            <div class="modal-dialog small">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="add-quote-tags">Add quotation</h4>
                </div>
                <div class="modal-body">
                  <div class="form-group">
                    <label for="selected-quote">Selection</label>
                    <textarea class="form-control serif js-quote-selection" id="selected-quote" style="resize: none;font-size: inherit" rows="4"></textarea>
                  </div>
                  <div class="form-group">
                    <label for="tags-list">Tags (comma-separated)</label>
                    <input type="text" class="form-control js-quote-tags" style="font-size: inherit" id="tags-list" placeholder="Enter tags">
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary btn-sm js-save-quote-modal">Save quote</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-2 js-sidebar"></div>
      </div>
    </div>
  </div>
  <div class="modal spinner-modal" data-backdrop="static">
    <div class="modal-dialog-custom">
      <div class="spinner-modal-content">
        <div class="modal-body-custom text-center">
          <i class="fa fa-spinner fa-spin-faster"></i>
        </div>
      </div>
    </div>
  </div>
  <%= render 'layouts/ga' if Rails.env.production? %>
</body>
</html>